site_name: "Entity: wiki"
repo_url: https://github.com/entity-toolkit/entity
repo_name: entity
# site_url: https://entity-toolkit.github.io/wiki/
site_url: https://haykh.github.io/entity-wiki-test/

nav:
  - Home: index.md
  - Getting started:
      - content/1-getting-started/1-compile-run.md
      - content/1-getting-started/2-dependencies.md
      - content/1-getting-started/3-inputfile.md
      - content/1-getting-started/4-units.md
      - content/1-getting-started/5-vis.md
      - content/1-getting-started/6-checkpoints.md
      - content/1-getting-started/7-docs.md
      - content/1-getting-started/8-docker.md
      - content/1-getting-started/9-faq.md
  - Understanding the code:
      - content/2-code/1-pic.md
      - content/2-code/2-hierarchy.md
      - content/2-code/3-domains.md
      - content/2-code/4-fields_particles.md
      - content/2-code/5-metrics.md
      - content/2-code/6-problem_generators.md
      - content/2-code/7-guidelines.md
  - Useful things:
      - content/useful/cluster-setups.md
      - content/useful/float-comparison.md
      - content/useful/theory_pic.md
      - content/useful/ks.md
  - Fun:
      - content/fun/coords.md
      - content/fun/cubed_sphere.md
  - Events:
      - content/events/sceecs2024/instructions.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid-diagram
          class: mermaid-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
  - attr_list
  - admonition
  - md_in_html
  # - footnotes
  # - def_list
  # - neoteroi.cards
  # - neoteroi.timeline

plugins:
  - tags
  - search
  - macros

use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo.svg
  logo: assets/logo.svg
  icon:
    repo: simple/git
    annotation: material/plus-circle-outline

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ntt-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: ntt-dark
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: "DM Sans"
    code: "JetBrains Mono"
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - search.highlight
    # - navigation.prune
    # - navigation.top
    # - navigation.instant

extra_css:
  - css/style.css

extra:
  social:
    - icon: fontawesome/brands/git
      link: https://github.com/entity-toolkit/entity/

copyright: Copyright &copy; 2021++, Entity dev team
