site_name: "Entity: wiki"
repo_url: https://github.com/entity-toolkit/entity
repo_name: entity
site_url: https://entity-toolkit.github.io/wiki

nav:
  - Home: index.md
  - Getting started:
      - Compiling/running: content/getting-started/compile-run.md
      - Dependencies: content/getting-started/dependencies.md
      - Docker: content/getting-started/docker.md
      - Input file: content/getting-started/inputfile.md
      # - Writing a problem generator: getting-started/pgen.md
      - Understanding the units: content/getting-started/units.md
      - Output & visualization: content/getting-started/vis.md
      - Writing checkpoints & restarting: content/getting-started/checkpoints.md
      - Documenting: content/getting-started/docs.md
      - F.A.Q.: content/getting-started/faq.md
  - Understanding the code:
      - content/code/pic.md
      - content/code/hierarchy.md
      - content/code/domains.md
      - content/code/fields_particles.md
      - content/code/metrics.md
      - content/code/problem_generators.md
      - content/code/guidelines.md
      # - "code/structure.md"
  - Useful things:
      - Floating point comparison: content/useful/float-comparison.md
      - Theory behind PIC: content/useful/theory_pic.md
      - Kerr metric: content/useful/ks.md
  - Fun:
      - Axisymmetric coordinates: content/fun/coords.md
      - Cubed sphere: content/fun/cubed_sphere.md
  - Events:
      - SCEECS Summer School 2024: content/events/sceecs2024/instructions.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - neoteroi.cards
  - neoteroi.timeline

plugins:
  - tags
  - search
  - macros
  - extra-sass

use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo.svg
  logo: assets/logo.svg
  icon:
    repo: simple/git
    annotation: material/plus-circle-outline

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ntt-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: ntt-dark
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: "DM Sans"
    code: "JetBrains Mono"
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    # - navigation.prune
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - search.highlight
    # - navigation.top
    # - navigation.instant

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  - css/tikzjax/fonts.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - js/tikzjax.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/entity-toolkit/entity/

copyright: Copyright &copy; 2021++, Entity dev team
