site_name: "Entity: wiki"
repo_url: https://github.com/entity-toolkit/entity
repo_name: entity
site_url: https://entity-toolkit.github.io/wiki

nav:
  - Home: index.md
  - Getting started:
      - Compiling/running: getting-started/compile-run.md
      - Writing a problem generator: getting-started/pgen.md
      - Understanding the units: getting-started/units.md
      - Output & visualization: getting-started/vis.md
      - Documenting: getting-started/docs.md
  - 3+1 formulation: "3p1.md"
  - PIC algorithm: "numerics/pic.md"
  - Understanding the code:
      - "code/metrics.md"
      - "code/domains.md"
      - "code/structure.md"
  - Useful things:
      - Floating point comparison: "useful/float-comparison.md"
      - Kerr metric: "useful/ks.md"
  - Fun:
      - Axisymmetric coordinates: "fun/coords.md"
      - Cubed sphere: "fun/cubed_sphere.md"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - neoteroi.cards
  - neoteroi.timeline

plugins:
  - tags
  - search
  - macros
  - extra-sass

use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo.svg
  logo: assets/logo.svg
  icon:
    repo: simple/git
    admonition:
      abstract: material/code-json
    annotation: material/plus-circle-outline

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: "IBM Plex Sans"
    code: "JetBrains Mono"
  features:
    - navigation.tracking
    - navigation.prune
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - content.tooltips
    - header.autohide
    # - navigation.top
    # - navigation.instant

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  # - https://tikzjax.com/v1/fonts.css
  - css/tikzjax/fonts.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - js/tikzjax.js
  # - https://tikzjax.com/v1/tikzjax.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/entity-toolkit/entity/

copyright: Copyright &copy; 2021++, Entity dev team
